v4 migration guide
layer0-docs/layer0-docs pull request #160
Opened 2021-12-10 17:28 UTC by tristanlee85

2021-12-13 16:12 UTC, tristanlee85 commented
@ierceg can you review this to make sure I didn't leave anything out in migrating from v3 to v4?

2021-12-16 02:12 UTC, ierceg requested changes

2021-12-16 02:12 UTC, ierceg commented on guides/layer0_migration.md
> +This guide describes what you need to know when migrating from version 2.x.x to version 3.x.x. Note that you can continue to use version 2.x.x but we highly recommend upgrading to version 3.x.x. The
I think it's time to deprecate this guide. There should be just one guide: from v1/2/3 to v4. All other versions have been deprecated.

2021-12-16 02:12 UTC, ierceg commented on guides/layer0_migration_v4.md
> +Once you deploy the new version of Layer0, your Edge links will change to have the format `*.layer0-limelight.link`. Your current edge links will switch to the new format on the next deployment for t
```suggestion
Once you deploy the new version of Layer0, your Edge links will change to have the format `*.layer0-limelight.link`. Your current edge links will switch to the new format on the next deployment for that environment. Old edge links may continue to work correctly for a while but they are considered deprecated and will be turned off without further notice. Permalinks will remain `*.free.layer0-perma.link`.
```

2021-12-16 02:12 UTC, ierceg commented on guides/layer0_migration_v4.md
> +You will see 2 different DNS configurations. If you are using a sub-domain, you will need to update the CNAME record with the value provided. If you are using an apex domain, you will need to update
```suggestion
You will see two different DNS configurations. If you are using a sub-domain, you will need to update the CNAME record with the value provided. If you are using an apex domain, you will need to update the A records to match the Anycast IP addresses listed.
```

2021-12-17 16:21 UTC, tristanlee85 commented on guides/layer0_migration.md
> +This guide describes what you need to know when migrating from version 2.x.x to version 3.x.x. Note that you can continue to use version 2.x.x but we highly recommend upgrading to version 3.x.x. The
Is it safe to assume that 1/2/3 > 4 is the same process? I can't recall much about 1.x.

2021-12-21 15:45 UTC, ierceg commented on guides/layer0_migration.md
> +This guide describes what you need to know when migrating from version 2.x.x to version 3.x.x. Note that you can continue to use version 2.x.x but we highly recommend upgrading to version 3.x.x. The
It is safe to assume, yes.

2021-12-22 17:57 UTC, merged