Steve b murphy branch
layer0-docs/layer0-docs pull request #164
Opened 2021-12-13 22:10 UTC by Steve-B-Murphy

I created changes for XDN-14305:
- Added `bots.md` to `/guides`
- Added an entry for `bots.md` to `guides.json

2021-12-13 22:22 UTC, Steve-B-Murphy commented
@ierceg, please review bots.md:

- Make sure I've explained the background correctly in General Information.
- Make sure the list in the table is complete and that the descriptions are correct.

Thanks!

2021-12-14 12:24 UTC, ierceg requested changes

2021-12-14 12:24 UTC, ierceg commented on guides/bots.md
> +|yahoo|Another Yahoo Search robot for crawling and indexing web page information.|
```suggestion
|yahoo|Another Yahoo Search robot for crawling and indexing web page information.|

If the included list is not accurate enough for you, you can easily add your own bot detection through [EdgeJS](... unsure what would be the link here... maybe https://docs.layer0.co/guides/routing ...) and its [`match`](/docs/api/core/classes/_router_router_.router.html#match) and [`setRequestHeader`](/docs/api/core/classes/_router_responsewriter_.responsewriter.html#setrequestheader) APIs:

<start code block>
router.match(
  {
    headers: {
      'user-agent': /^regex-for-your-bot-detection$/i
    },
  },
  ({ setRequestHeader }) => {
    setRequestHeader('my-bot-detection-is-bot', '1')
  }
)
<end code block>

```

2021-12-14 21:20 UTC, Steve-B-Murphy commented
I made one change to Ivan's suggestions and accepted all others

2021-12-14 22:36 UTC, jeffpatzer approved these changes

2021-12-14 22:37 UTC, merged