Update getting started guide
layer0-docs/layer0-docs pull request #212
Opened 2021-12-20 14:57 UTC by rishi-raj-jain

2021-12-20 15:27 UTC, jeffpatzer requested changes

2021-12-20 15:27 UTC, jeffpatzer commented on guides/webapp_cdn_getting_started.md
> +  updateResponseHeader('location', /https:\/\/origin.site.com\//gi, '/')
@rishi-raj-jain can you do a couple things here: 

1. Add a comment to explain the step
2. Leave the step commented. This would require someone to actually set `origin.site.com` and because of that it needs to be opt in for now.

2021-12-20 15:58 UTC, rishi-raj-jain commented on guides/webapp_cdn_getting_started.md
> +  updateResponseHeader('location', /https:\/\/origin.site.com\//gi, '/')
I think this page misses addressing layer0.config.js at whole. 
Is that due to some reason or I can go ahead and add explanation for that too?
The origin.site.com is taken from the first image on the page, and the guide assumes that the user is aware of what's required in layer0.config.js.

2021-12-20 21:24 UTC, jeffpatzer commented on guides/webapp_cdn_getting_started.md
> +  updateResponseHeader('location', /https:\/\/origin.site.com\//gi, '/')
We should add an explanation to `layer0.config.js`, but I don't think adding a location header rewrite here is the right spot for it. The "Getting started" is about making it as simple as possible. With that in mind, I'm thinking it makes sense to not include that here. They can go to EdgeJs routing for more details.

2021-12-21 07:28 UTC, rishi-raj-jain commented on guides/webapp_cdn_getting_started.md
> +  updateResponseHeader('location', /https:\/\/origin.site.com\//gi, '/')
I do get where you're thinking it from, but from a perspective of an onboarding user, I'm neither aware of where do I need to go (and how specifically `edgejs routing` to specifically control redirects in case 201s and 3XXs (based on the location header)), and neither I see an example of updating location header on [EdgeJS Routing](https://docs.layer0.co/guides/routing).
I'd say we still include it as part of it in the getting started because that's a requirement for a smooth experience with those response codes, which one can't find easily on docs.layer0.co (screenshot as attached, nothing in search that helps).
<img width="513" alt="Screenshot 2021-12-21 at 12 57 17 PM" src="https://user-images.githubusercontent.com/46300090/146888906-9e694a4b-41bc-4455-a48b-54140b105fd6.png">

2021-12-23 16:21 UTC, jeffpatzer commented on guides/webapp_cdn_getting_started.md
> +  updateResponseHeader('location', /https:\/\/origin.site.com\//gi, '/')
I see what you are saying, but not keeping the script simple and not overloading it with boilerplate is also important. What if we add a section that specifically addresses redirects in the EdgeJS routing page or similar. This way if you search for it, it will show up? 

I think finding the balance between the first project and providing too many edge case examples at the time of just starting, leads to more confusion than anything. But if we make it easy to locate the piece of information one is looking for, it lets someone expand and address their issues as they become one.

2021-12-23 19:27 UTC, tristanlee85 commented on guides/webapp_cdn_getting_started.md
> +  updateResponseHeader('location', /https:\/\/origin.site.com\//gi, '/')
I am not sure I understand the change. Why are we proxying from the origin but also sending a redirect?

2022-01-03 19:25 UTC, jeffpatzer commented on guides/webapp_cdn_getting_started.md
> +  updateResponseHeader('location', /https:\/\/origin.site.com\//gi, '/')
@tristanlee85 i believe its a line to change redirects by removing the hardcoded origin domain. In order to keep someone on the actual right domain.

2022-01-03 19:27 UTC, jeffpatzer approved these changes

2022-01-03 19:27 UTC, merged