Simplify getting started guide
layer0-docs/layer0-docs pull request #224
Opened 2022-01-04 09:44 UTC by rishi-raj-jain

2022-01-04 09:50 UTC, rishi-raj-jain commented
Questions on the following:
"Once your project code is up and running, you can view its performance from within the [app.layer0.co]({{ APP_URL }}) cockpit. Using the tools available here, you can understand the caching behavior of the routes you have added. Continue adding routes and dialing in your config until you are ready to launch the site and code."

1. Where can I evaluate my core web vitals aka performance on the site that I just deployed? Is that possible without me manually adding Layer0 RUM?
2. What is meant by understanding the `understand the caching behavior` from my project on app.layer0.co?
3. Where's my config to which I'll add my routes to?

Overall this seems like it's written from the point of view of an existing user, and not someone who's just starting with Layer0.

cc @jeffpatzer

2022-01-04 15:06 UTC, jeffpatzer requested changes
@rishi-raj-jain thanks for the changes on this, some comments in regards to the review are below, will answer you questions separately

2022-01-04 15:06 UTC, jeffpatzer commented on guides/webapp_cdn_getting_started.md
> +npm i -g {{ PACKAGE_NAME }}/cli // yarn global add {{ PACKAGE_NAME }}/cli
`//` is not a bash comment, let's go with 

```
npm i -g {{ PACKAGE_NAME }}/cli
# yarn global add {{ PACKAGE_NAME }}/cli
```

2022-01-04 15:06 UTC, jeffpatzer commented on guides/webapp_cdn_getting_started.md
> +- `shoppingFlowRouteHandler.ts`: implements caching rules,
This should actually just be `route-handler.ts`
Check the default generator to see changes: https://github.com/layer0-docs/layer0-templates/tree/main/default/src

2022-01-04 15:06 UTC, jeffpatzer commented on guides/webapp_cdn_getting_started.md
> +- `service-worker.ts`: prefetches content and stores in cache,
Since these are bullets they should not have commas.

2022-01-04 15:12 UTC, jeffpatzer commented
> Questions on the following (the paragraph right after `0 deploy` on this guide)
> 
> "Once your project code is up and running, you can view its performance from within the [app.layer0.co]({{ APP_URL }}) cockpit. Using the tools available here, you can understand the caching behavior of the routes you have added. Continue adding routes and dialing in your config until you are ready to launch the site and code."
> 
> 1. Where can I evaluate my core web vitals aka performance on the site that I just deployed? Is that possible without me manually adding Layer0 RUM?

I do not believe this is referring to Core Web Vitals, but performance surrounding caching. To add RUM you have to enable via instructions provided here: https://docs.layer0.co/guides/core_web_vitals

> 2. What is meant by understanding the `understand the caching behavior` from my project on app.layer0.co?

Caching on the defined routes in `routes.ts`

> 3. Where's my config to which I'll add my routes to?

Paths and cache configs provided (https://github.com/layer0-docs/layer0-templates/blob/main/default/src/cache.ts)

> 
> Overall this seems like it's written from the point of view of an existing user, and not someone who's just starting with Layer0.
> 
> cc @jeffpatzer

I think you're questions are valid. I think adding links to specific areas from within the paragraph should provide the necessary context to link someone out.

2022-01-05 04:47 UTC, rishi-raj-jain commented on guides/webapp_cdn_getting_started.md
> +npm i -g {{ PACKAGE_NAME }}/cli // yarn global add {{ PACKAGE_NAME }}/cli
Right about that. Resolved.

2022-01-05 05:02 UTC, rishi-raj-jain commented
> > Questions on the following (the paragraph right after `0 deploy` on this guide)
> > "Once your project code is up and running, you can view its performance from within the [app.layer0.co]({{ APP_URL }}) cockpit. Using the tools available here, you can understand the caching behavior of the routes you have added. Continue adding routes and dialing in your config until you are ready to launch the site and code."
> > 
> > 1. Where can I evaluate my core web vitals aka performance on the site that I just deployed? Is that possible without me manually adding Layer0 RUM?
> 
> I do not believe this is referring to Core Web Vitals, but performance surrounding caching. To add RUM you have to enable via instructions provided here: https://docs.layer0.co/guides/core_web_vitals
> 
> > 2. What is meant by understanding the `understand the caching behavior` from my project on app.layer0.co?
> 
> Caching on the defined routes in `routes.ts`
> 
> > 3. Where's my config to which I'll add my routes to?
> 
> Paths and cache configs provided (https://github.com/layer0-docs/layer0-templates/blob/main/default/src/cache.ts)
> 
> > Overall this seems like it's written from the point of view of an existing user, and not someone who's just starting with Layer0.
> > cc @jeffpatzer
> 
> I think you're questions are valid. I think adding links to specific areas from within the paragraph should provide the necessary context to link someone out.

I think it requires a re-wording/re-thinking as to
- what is wanted out of this text in terms of how user can gain from it,
- and why is this needed? assume that I'm a new user, and I'm already happy that I've deployed a site with Layer0 successfully.

2022-01-05 14:35 UTC, rishi-raj-jain commented
Updated the guide to include example link, deploy button and view code. Assisting PR: https://github.com/layer0-docs/layer0-cdn-example/pull/2

2022-01-05 15:33 UTC, jeffpatzer commented
Yup, we'll keep working on the language.

2022-01-05 15:34 UTC, jeffpatzer approved these changes

2022-01-05 15:34 UTC, merged