Commit all needed changes
layer0-docs/layer0-docs pull request #267
Opened 2022-02-04 19:24 UTC by Steve-B-Murphy

Please review changes.

2022-02-10 16:01 UTC, tristanlee85 commented on guides/routing.md
> +You define routes for {{ PACKAGE_NAME }} using the `routes.js` file.
```suggestion
You define routes for {{ PRODUCT_NAME }} using the `routes.js` file.
```

2022-02-10 16:02 UTC, tristanlee85 commented on guides/routing.md
> +- For an existing project where you have already run `@layer0/cli@latest init`, the file already exists at the route of your project; modify the it as needed.
```suggestion
- For an existing project where you have already run `0 init`, the file already exists at the root of your project; modify the file as needed.
```

2022-02-10 19:08 UTC, tristanlee85 requested changes

2022-02-10 19:08 UTC, tristanlee85 commented on guides/routing.md
The wording around this is not accurate. We shouldn't be telling the user to manually create a `routes.ts` file. Instead, instructions should either be added here on the process for running `init` or a link with wording that directs them to the getting started sections that explains the init process and how to run it.

2022-02-10 19:08 UTC, tristanlee85 commented on guides/webapp_cdn_getting_started.md
> +After you run npx `@layer0/cli@latest init`, {{ PRODUCT_NAME }} creates the following files:
```suggestion
After you run `{{ CLI_NAME }} init`, {{ PRODUCT_NAME }} creates the following files:
```

2022-02-10 19:08 UTC, tristanlee85 commented on guides/webapp_cdn_getting_started.md
> +After you run npx `@layer0/cli@latest init`, {{ PRODUCT_NAME }} creates the following files:
Also, line 44 should be changed to `{{ CLI_NAME }} init` as well. Line 38 gives them the option to install with npm or yarn, but we reference `npx` which wouldn't be accurate if they installed with yarn.

2022-02-10 22:39 UTC, Steve-B-Murphy commented on guides/routing.md
@tristanlee85 Thanks. Please confirm the following:

In the `Configuration` section I will change the content so it reads as follows:

`You define routes for @layer0 using the routes.js file.

Before continuing, create your Layer0 project using instructions in _<insert reference to "Create a New Layer0 Project" section in webapp_cdn_getting_started.md_>. You can override the default path to the router by setting the routes key in layer0.config.js.

The routes.js file should export an instance of @layer0/core/router/Router:`

Does that sound right?

2022-02-11 15:32 UTC, tristanlee85 commented on guides/routing.md
> **You define routes for{{ PRODUCT_NAME }} using the routes.js file.
> 
> Before continuing, if you have not already initialized your project with {{ PRODUCT_NAME }}, refer to these instructions in <insert reference to "Create a New Layer0 Project" section in webapp_cdn_getting_started.md>.
> 
> The routes.js file should export an instance of @layer0/core/router/Router:**

2022-02-11 18:48 UTC, tristanlee85 commented on guides/webapp_cdn_getting_started.md
>  ```
I would split this out into 2 different code blocks for npm and yarn. With the comments being in there, it may throw an error if the user tries to click the copy button and paste everything into the terminal.

2022-02-11 19:07 UTC, Steve-B-Murphy commented on guides/webapp_cdn_getting_started.md
>  ```
Yes. I was thinking about doing that.

2022-02-11 19:44 UTC, merged