Update ExampleButtons.tsx
layer0-docs/layer0-docs pull request #425
Opened 2022-07-22 01:35 UTC by rishi-raj-jain

2022-07-22 19:51 UTC, tristanlee85 commented
@rishi-raj-jain has Gaby had a chance to look at this? The button goes with our brand scheme, but it looks out of place next to the others. What if we kept it how the existing button is except change out the left logo?

2022-08-02 14:47 UTC, tristanlee85 commented
Working to move this to embedded SVG instead of network request for image.

2022-08-02 15:02 UTC, rishi-raj-jain commented
@tristanlee85 That sounds great! Hope we can also keep the asset on docs.layer0.co/button.svg so that the references in README's and on https://docs.layer0.co/guides/deploy_to_layer0 get updated as well.

2022-08-04 17:23 UTC, tristanlee85 requested changes

2022-08-04 17:23 UTC, tristanlee85 commented on src/components/MDX/ExampleButtons.tsx
> +        </a>
I would prefer we update the `<ButtonLink type="deploy" ... />` with this new icon instead so it can be easily used elsewhere.

2022-08-04 20:46 UTC, rishi-raj-jain commented
https://layer0-docs-xdn-docs-add-deploy-button-2202.alt.layer0-docs.layer0-perma.link/guides/contributing

2022-08-05 16:39 UTC, tristanlee85 requested changes

2022-08-05 16:39 UTC, tristanlee85 commented on src/pages/guides/bloomreach.mdx
> +## Example {/* example */}
Do you have a formatter that pads these with spaces? This will break the anchor tags.

2022-08-05 17:09 UTC, rishi-raj-jain commented on src/pages/guides/bloomreach.mdx
> +## Example {/* example */}
I think it follows what prettier says it to...

2022-08-05 17:10 UTC, rishi-raj-jain commented on src/pages/guides/bloomreach.mdx
> +## Example {/* example */}
and prettier doesn't ignore it as inside .prettierignore it says guides ending with .md but not .mdx.

2022-08-05 17:35 UTC, tristanlee85 commented on src/pages/guides/bloomreach.mdx
> +## Example {/* example */}
Ahh, didn't realize it was `mdx` file. That would explain why I rarely see. I will fix it up. 👍

2022-08-06 05:36 UTC, rishi-raj-jain commented on src/pages/guides/bloomreach.mdx
> +## Example {/* example */}
@tristanlee85 Thanks!

2022-08-08 20:54 UTC, tristanlee85 submitted a review, later dismissed

2022-08-08 20:56 UTC, tristanlee85 approved these changes

2022-08-08 21:02 UTC, merged