jeff/add-debugging-guide
layer0-docs/layer0-docs pull request #47
Opened 2021-08-26 22:59 UTC by jeffpatzer

- Added to troubleshooting guide
- Cleaned up some console errors (MUI complaints)
- Bumped packages for security

![image](https://user-images.githubusercontent.com/178291/131046860-526f2eb7-1f46-4106-9b0e-0e249b58ed3a.png)
Active menu item is just bold, no need for the bullet point

2021-09-01 04:10 UTC, rishi-raj-jain commented on guides/troubleshooting.md
> +We provide a header, `x-0-caching-status` to best understand why something is being cached. There is a [detailed guide](guides/caching#section_why_is_my_response_not_being_cached_) available on decip
decipering -> deciphering?

2021-09-07 14:03 UTC, jeffpatzer commented on guides/troubleshooting.md
> +We provide a header, `x-0-caching-status` to best understand why something is being cached. There is a [detailed guide](guides/caching#section_why_is_my_response_not_being_cached_) available on decip
Nice catch

2021-09-07 14:07 UTC, rishi-raj-jain commented on guides/nuxt.md
> +  'api/**/*': true,
does just 
includeFiles : {
    api: true
} 
work fine?

2021-09-07 14:10 UTC, rishi-raj-jain commented on guides/nuxt.md
> +Nuxt requires that certain resources are included in a build and deploy to have access to them. As such, at times this will require additional configuration. To include additional resources for serve
maybe worth mentioning that if one wants to include some packages that aren't covered in includeNodeModules: true, that can be done via includeFiles like the following:
includeFiles: {
     'node_modules/some_pakage/**/*': true
}

2021-09-07 18:44 UTC, jeffpatzer commented on guides/nuxt.md
> +  'api/**/*': true,
It looks like it does, but that does not really line up with the [docs](https://docs.layer0.co/guides/v3.16.5/layer0_config#section_includefiles) that we already have. I'd rather stay consistent.

2021-09-07 18:47 UTC, jeffpatzer commented on guides/nuxt.md
> +Nuxt requires that certain resources are included in a build and deploy to have access to them. As such, at times this will require additional configuration. To include additional resources for serve
Good tip. Added.

2021-09-13 15:13 UTC, jeffpatzer commented
@tristanlee85 can you review this? i want to get the PR merged

2021-09-13 16:15 UTC, tristanlee85 requested changes

2021-09-13 16:15 UTC, tristanlee85 commented on components/Toc.js
> -      />
This styling has been here for a while. Was it requested to be removed?

2021-09-13 16:15 UTC, tristanlee85 commented on components/nav/Link.js
> -  )
Same as above ^^

2021-09-13 16:15 UTC, tristanlee85 commented on guides/troubleshooting.md
> +By viewing the server logs in the {{ PRODUCT_NAME }} Developer Console, you can see all of the messages logged by your application using console.log, console.warn, etc...
```suggestion
By viewing the server logs in the {{ PRODUCT_NAME }} Developer Console, you can see all of the messages logged by your application using `console.log`, `console.warn`, etc...
```

2021-09-13 16:15 UTC, tristanlee85 commented on guides/troubleshooting.md
> +Connect directly to the address listed after. This is good for sending a request straight to origin and bypassing L0, or testing a connection to Layer0 before DNS cutover. Setting up a localhost DNS
```suggestion
Connect directly to the address listed after. This is good for sending a request straight to origin and bypassing Layer0, or testing a connection to Layer0 before DNS cutover. Setting up a localhost DNS configuration is usually better for this if possible.
```

2021-09-13 16:15 UTC, tristanlee85 commented on guides/troubleshooting.md
> +Adding a `layer0_debug=true` to the query parameter will skip the cache and make it easy to check for dynamic data (i.e. personalized content). Append grep to search for something you might want.
```suggestion
Adding a `layer0_debug=true` to the query parameter will skip the cache and make it easy to check for dynamic data (i.e. personalized content). Append `grep` to search for something you might want.
```

> Append `grep` to search for something you might want.

Maybe something like:
> Append `grep` to search for a specific value in the response output.

(or something along those lines?)

2021-09-13 17:44 UTC, jeffpatzer commented on components/Toc.js
> -      />
Specifically, no. But I asked Mark about doing these type of updates and he said to go for it.

2021-09-13 17:45 UTC, jeffpatzer commented
@tristanlee85 answered your comments

2021-09-13 18:19 UTC, tristanlee85 approved these changes

2021-09-13 18:21 UTC, merged