Update routing.md
layer0-docs/layer0-docs pull request #488
Opened 2022-09-01 10:59 UTC by rishi-raj-jain

2022-09-01 11:25 UTC, letrest requested changes
why not keep it in the static directory @rishi-raj-jain ?

2022-09-01 11:29 UTC, rishi-raj-jain commented
> why not keep it in the static directory @rishi-raj-jain ?

I think that having static there, is an added complexity for understanding the purpose of .catch.

As a naive user, It would make it seem that for handling error codes with serveStatic would require a static folder to be placed with that custom page.

2022-09-01 16:07 UTC, tristanlee85 commented on src/pages/guides/routing.md
> +For example, to issue a custom error page when the origin returns any 53x status code:
Why is this specifically targeting platform error codes? Can we just blanket it to `5XX`?

2022-09-02 19:28 UTC, tristanlee85 approved these changes

2022-09-03 14:06 UTC, merged